# Generated by Django 5.2.6 on 2025-09-26 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_profile_date_of_birth_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
