# Generated by Django 5.2.6 on 2025-09-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='revenue',
            field=models.BigIntegerField(default=0),
        ),
    ]
