# Generated by Django 5.2.6 on 2025-09-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_movie_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cinematographer',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
