# Generated by Django 5.2.6 on 2025-09-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_director_producer_movie_directors_movie_producers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_movies_viewed',
        ),
    ]
