# Generated by Django 5.2.6 on 2025-10-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_remove_person_name_uniqueness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.CreateModel(
            name='MovieCastCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.movie')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
