# Generated by Django 5.2.6 on 2025-10-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_remove_movie_actors_moviecastcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(through='tracker.MovieCastCredit', to='tracker.actor'),
        ),
    ]
