# Generated by Django 5.2.6 on 2025-10-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='collection_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='collection_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
